pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
   stage('Test') {
            steps {
                echo 'Running tests with all...'
                // Example: Run tests
                sh 'mvn test'
            }
        }     
      }
    }
  }
}
